apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fy22bh8wl-python
  janus-idp.io/tekton: fy22bh8wl-python
  backstage.io/kubernetes-id: fy22bh8wl-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fy22bh8wl-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
